baseURL = 'https://cchesser.github.io/nrql-bonanza/'
languageCode = 'en-us'
title = 'NRQL Bonanza'
theme = ["github.com/dzello/reveal-hugo"]

[params.reveal_hugo]
highlight_theme = "github"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

